apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"php-helloworld:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"php-helloworld\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2023-08-18T06:45:52Z"
    generation: 3
    labels:
      app: php-helloworld
      app.kubernetes.io/component: php-helloworld
      app.kubernetes.io/instance: php-helloworld
    name: php-helloworld
    namespace: rbehddl0717-s2i
    resourceVersion: "13092926"
    uid: 990670ed-0e17-486d-b000-7a16f249e1f8
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: php-helloworld
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: php-helloworld
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/rbehddl0717-s2i/php-helloworld@sha256:eaa444a3829ac0435f412d50de0d52668e62b46ad8d2159be43d71d7daecb199
          imagePullPolicy: IfNotPresent
          name: php-helloworld
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2023-08-18T06:45:52Z"
      lastUpdateTime: "2023-08-18T06:45:52Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2023-08-18T06:45:52Z"
      lastUpdateTime: "2023-08-18T06:45:52Z"
      message: 'Pod "php-helloworld-7c49dd9597-lqzhk" is invalid: spec.containers[0].image:
        Invalid value: " ": must not have leading or trailing whitespace'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    - lastTransitionTime: "2023-08-18T06:45:52Z"
      lastUpdateTime: "2023-08-18T06:46:17Z"
      message: ReplicaSet "php-helloworld-644b7b99c8" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 3
    replicas: 1
    unavailableReplicas: 2
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
